// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UserCache.proto

package n3.sail.protobuf.schema;

public final class UserCacheSchema {
  private UserCacheSchema() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface UserCacheDTOOrBuilder extends
      // @@protoc_insertion_point(interface_extends:tutorial.UserCacheDTO)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.tutorial.CoreAccountDTO coreAccountDTO = 1;</code>
     */
    boolean hasCoreAccountDTO();
    /**
     * <code>.tutorial.CoreAccountDTO coreAccountDTO = 1;</code>
     */
    n3.sail.protobuf.schema.UserCacheSchema.CoreAccountDTO getCoreAccountDTO();
    /**
     * <code>.tutorial.CoreAccountDTO coreAccountDTO = 1;</code>
     */
    n3.sail.protobuf.schema.UserCacheSchema.CoreAccountDTOOrBuilder getCoreAccountDTOOrBuilder();

    /**
     * <code>.tutorial.OperatorDTO operatorDTO = 2;</code>
     */
    boolean hasOperatorDTO();
    /**
     * <code>.tutorial.OperatorDTO operatorDTO = 2;</code>
     */
    n3.sail.protobuf.schema.UserCacheSchema.OperatorDTO getOperatorDTO();
    /**
     * <code>.tutorial.OperatorDTO operatorDTO = 2;</code>
     */
    n3.sail.protobuf.schema.UserCacheSchema.OperatorDTOOrBuilder getOperatorDTOOrBuilder();
  }
  /**
   * Protobuf type {@code tutorial.UserCacheDTO}
   */
  public  static final class UserCacheDTO extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:tutorial.UserCacheDTO)
      UserCacheDTOOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use UserCacheDTO.newBuilder() to construct.
    private UserCacheDTO(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private UserCacheDTO() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private UserCacheDTO(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              n3.sail.protobuf.schema.UserCacheSchema.CoreAccountDTO.Builder subBuilder = null;
              if (coreAccountDTO_ != null) {
                subBuilder = coreAccountDTO_.toBuilder();
              }
              coreAccountDTO_ = input.readMessage(n3.sail.protobuf.schema.UserCacheSchema.CoreAccountDTO.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(coreAccountDTO_);
                coreAccountDTO_ = subBuilder.buildPartial();
              }

              break;
            }
            case 18: {
              n3.sail.protobuf.schema.UserCacheSchema.OperatorDTO.Builder subBuilder = null;
              if (operatorDTO_ != null) {
                subBuilder = operatorDTO_.toBuilder();
              }
              operatorDTO_ = input.readMessage(n3.sail.protobuf.schema.UserCacheSchema.OperatorDTO.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(operatorDTO_);
                operatorDTO_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return n3.sail.protobuf.schema.UserCacheSchema.internal_static_tutorial_UserCacheDTO_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return n3.sail.protobuf.schema.UserCacheSchema.internal_static_tutorial_UserCacheDTO_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              n3.sail.protobuf.schema.UserCacheSchema.UserCacheDTO.class, n3.sail.protobuf.schema.UserCacheSchema.UserCacheDTO.Builder.class);
    }

    public static final int COREACCOUNTDTO_FIELD_NUMBER = 1;
    private n3.sail.protobuf.schema.UserCacheSchema.CoreAccountDTO coreAccountDTO_;
    /**
     * <code>.tutorial.CoreAccountDTO coreAccountDTO = 1;</code>
     */
    public boolean hasCoreAccountDTO() {
      return coreAccountDTO_ != null;
    }
    /**
     * <code>.tutorial.CoreAccountDTO coreAccountDTO = 1;</code>
     */
    public n3.sail.protobuf.schema.UserCacheSchema.CoreAccountDTO getCoreAccountDTO() {
      return coreAccountDTO_ == null ? n3.sail.protobuf.schema.UserCacheSchema.CoreAccountDTO.getDefaultInstance() : coreAccountDTO_;
    }
    /**
     * <code>.tutorial.CoreAccountDTO coreAccountDTO = 1;</code>
     */
    public n3.sail.protobuf.schema.UserCacheSchema.CoreAccountDTOOrBuilder getCoreAccountDTOOrBuilder() {
      return getCoreAccountDTO();
    }

    public static final int OPERATORDTO_FIELD_NUMBER = 2;
    private n3.sail.protobuf.schema.UserCacheSchema.OperatorDTO operatorDTO_;
    /**
     * <code>.tutorial.OperatorDTO operatorDTO = 2;</code>
     */
    public boolean hasOperatorDTO() {
      return operatorDTO_ != null;
    }
    /**
     * <code>.tutorial.OperatorDTO operatorDTO = 2;</code>
     */
    public n3.sail.protobuf.schema.UserCacheSchema.OperatorDTO getOperatorDTO() {
      return operatorDTO_ == null ? n3.sail.protobuf.schema.UserCacheSchema.OperatorDTO.getDefaultInstance() : operatorDTO_;
    }
    /**
     * <code>.tutorial.OperatorDTO operatorDTO = 2;</code>
     */
    public n3.sail.protobuf.schema.UserCacheSchema.OperatorDTOOrBuilder getOperatorDTOOrBuilder() {
      return getOperatorDTO();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (coreAccountDTO_ != null) {
        output.writeMessage(1, getCoreAccountDTO());
      }
      if (operatorDTO_ != null) {
        output.writeMessage(2, getOperatorDTO());
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (coreAccountDTO_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getCoreAccountDTO());
      }
      if (operatorDTO_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getOperatorDTO());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof n3.sail.protobuf.schema.UserCacheSchema.UserCacheDTO)) {
        return super.equals(obj);
      }
      n3.sail.protobuf.schema.UserCacheSchema.UserCacheDTO other = (n3.sail.protobuf.schema.UserCacheSchema.UserCacheDTO) obj;

      boolean result = true;
      result = result && (hasCoreAccountDTO() == other.hasCoreAccountDTO());
      if (hasCoreAccountDTO()) {
        result = result && getCoreAccountDTO()
            .equals(other.getCoreAccountDTO());
      }
      result = result && (hasOperatorDTO() == other.hasOperatorDTO());
      if (hasOperatorDTO()) {
        result = result && getOperatorDTO()
            .equals(other.getOperatorDTO());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasCoreAccountDTO()) {
        hash = (37 * hash) + COREACCOUNTDTO_FIELD_NUMBER;
        hash = (53 * hash) + getCoreAccountDTO().hashCode();
      }
      if (hasOperatorDTO()) {
        hash = (37 * hash) + OPERATORDTO_FIELD_NUMBER;
        hash = (53 * hash) + getOperatorDTO().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static n3.sail.protobuf.schema.UserCacheSchema.UserCacheDTO parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static n3.sail.protobuf.schema.UserCacheSchema.UserCacheDTO parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static n3.sail.protobuf.schema.UserCacheSchema.UserCacheDTO parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static n3.sail.protobuf.schema.UserCacheSchema.UserCacheDTO parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static n3.sail.protobuf.schema.UserCacheSchema.UserCacheDTO parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static n3.sail.protobuf.schema.UserCacheSchema.UserCacheDTO parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static n3.sail.protobuf.schema.UserCacheSchema.UserCacheDTO parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static n3.sail.protobuf.schema.UserCacheSchema.UserCacheDTO parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static n3.sail.protobuf.schema.UserCacheSchema.UserCacheDTO parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static n3.sail.protobuf.schema.UserCacheSchema.UserCacheDTO parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static n3.sail.protobuf.schema.UserCacheSchema.UserCacheDTO parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static n3.sail.protobuf.schema.UserCacheSchema.UserCacheDTO parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(n3.sail.protobuf.schema.UserCacheSchema.UserCacheDTO prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code tutorial.UserCacheDTO}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:tutorial.UserCacheDTO)
        n3.sail.protobuf.schema.UserCacheSchema.UserCacheDTOOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return n3.sail.protobuf.schema.UserCacheSchema.internal_static_tutorial_UserCacheDTO_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return n3.sail.protobuf.schema.UserCacheSchema.internal_static_tutorial_UserCacheDTO_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                n3.sail.protobuf.schema.UserCacheSchema.UserCacheDTO.class, n3.sail.protobuf.schema.UserCacheSchema.UserCacheDTO.Builder.class);
      }

      // Construct using n3.sail.protobuf.schema.UserCacheSchema.UserCacheDTO.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        if (coreAccountDTOBuilder_ == null) {
          coreAccountDTO_ = null;
        } else {
          coreAccountDTO_ = null;
          coreAccountDTOBuilder_ = null;
        }
        if (operatorDTOBuilder_ == null) {
          operatorDTO_ = null;
        } else {
          operatorDTO_ = null;
          operatorDTOBuilder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return n3.sail.protobuf.schema.UserCacheSchema.internal_static_tutorial_UserCacheDTO_descriptor;
      }

      public n3.sail.protobuf.schema.UserCacheSchema.UserCacheDTO getDefaultInstanceForType() {
        return n3.sail.protobuf.schema.UserCacheSchema.UserCacheDTO.getDefaultInstance();
      }

      public n3.sail.protobuf.schema.UserCacheSchema.UserCacheDTO build() {
        n3.sail.protobuf.schema.UserCacheSchema.UserCacheDTO result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public n3.sail.protobuf.schema.UserCacheSchema.UserCacheDTO buildPartial() {
        n3.sail.protobuf.schema.UserCacheSchema.UserCacheDTO result = new n3.sail.protobuf.schema.UserCacheSchema.UserCacheDTO(this);
        if (coreAccountDTOBuilder_ == null) {
          result.coreAccountDTO_ = coreAccountDTO_;
        } else {
          result.coreAccountDTO_ = coreAccountDTOBuilder_.build();
        }
        if (operatorDTOBuilder_ == null) {
          result.operatorDTO_ = operatorDTO_;
        } else {
          result.operatorDTO_ = operatorDTOBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof n3.sail.protobuf.schema.UserCacheSchema.UserCacheDTO) {
          return mergeFrom((n3.sail.protobuf.schema.UserCacheSchema.UserCacheDTO)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(n3.sail.protobuf.schema.UserCacheSchema.UserCacheDTO other) {
        if (other == n3.sail.protobuf.schema.UserCacheSchema.UserCacheDTO.getDefaultInstance()) return this;
        if (other.hasCoreAccountDTO()) {
          mergeCoreAccountDTO(other.getCoreAccountDTO());
        }
        if (other.hasOperatorDTO()) {
          mergeOperatorDTO(other.getOperatorDTO());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        n3.sail.protobuf.schema.UserCacheSchema.UserCacheDTO parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (n3.sail.protobuf.schema.UserCacheSchema.UserCacheDTO) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private n3.sail.protobuf.schema.UserCacheSchema.CoreAccountDTO coreAccountDTO_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          n3.sail.protobuf.schema.UserCacheSchema.CoreAccountDTO, n3.sail.protobuf.schema.UserCacheSchema.CoreAccountDTO.Builder, n3.sail.protobuf.schema.UserCacheSchema.CoreAccountDTOOrBuilder> coreAccountDTOBuilder_;
      /**
       * <code>.tutorial.CoreAccountDTO coreAccountDTO = 1;</code>
       */
      public boolean hasCoreAccountDTO() {
        return coreAccountDTOBuilder_ != null || coreAccountDTO_ != null;
      }
      /**
       * <code>.tutorial.CoreAccountDTO coreAccountDTO = 1;</code>
       */
      public n3.sail.protobuf.schema.UserCacheSchema.CoreAccountDTO getCoreAccountDTO() {
        if (coreAccountDTOBuilder_ == null) {
          return coreAccountDTO_ == null ? n3.sail.protobuf.schema.UserCacheSchema.CoreAccountDTO.getDefaultInstance() : coreAccountDTO_;
        } else {
          return coreAccountDTOBuilder_.getMessage();
        }
      }
      /**
       * <code>.tutorial.CoreAccountDTO coreAccountDTO = 1;</code>
       */
      public Builder setCoreAccountDTO(n3.sail.protobuf.schema.UserCacheSchema.CoreAccountDTO value) {
        if (coreAccountDTOBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          coreAccountDTO_ = value;
          onChanged();
        } else {
          coreAccountDTOBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.tutorial.CoreAccountDTO coreAccountDTO = 1;</code>
       */
      public Builder setCoreAccountDTO(
          n3.sail.protobuf.schema.UserCacheSchema.CoreAccountDTO.Builder builderForValue) {
        if (coreAccountDTOBuilder_ == null) {
          coreAccountDTO_ = builderForValue.build();
          onChanged();
        } else {
          coreAccountDTOBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.tutorial.CoreAccountDTO coreAccountDTO = 1;</code>
       */
      public Builder mergeCoreAccountDTO(n3.sail.protobuf.schema.UserCacheSchema.CoreAccountDTO value) {
        if (coreAccountDTOBuilder_ == null) {
          if (coreAccountDTO_ != null) {
            coreAccountDTO_ =
              n3.sail.protobuf.schema.UserCacheSchema.CoreAccountDTO.newBuilder(coreAccountDTO_).mergeFrom(value).buildPartial();
          } else {
            coreAccountDTO_ = value;
          }
          onChanged();
        } else {
          coreAccountDTOBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.tutorial.CoreAccountDTO coreAccountDTO = 1;</code>
       */
      public Builder clearCoreAccountDTO() {
        if (coreAccountDTOBuilder_ == null) {
          coreAccountDTO_ = null;
          onChanged();
        } else {
          coreAccountDTO_ = null;
          coreAccountDTOBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.tutorial.CoreAccountDTO coreAccountDTO = 1;</code>
       */
      public n3.sail.protobuf.schema.UserCacheSchema.CoreAccountDTO.Builder getCoreAccountDTOBuilder() {
        
        onChanged();
        return getCoreAccountDTOFieldBuilder().getBuilder();
      }
      /**
       * <code>.tutorial.CoreAccountDTO coreAccountDTO = 1;</code>
       */
      public n3.sail.protobuf.schema.UserCacheSchema.CoreAccountDTOOrBuilder getCoreAccountDTOOrBuilder() {
        if (coreAccountDTOBuilder_ != null) {
          return coreAccountDTOBuilder_.getMessageOrBuilder();
        } else {
          return coreAccountDTO_ == null ?
              n3.sail.protobuf.schema.UserCacheSchema.CoreAccountDTO.getDefaultInstance() : coreAccountDTO_;
        }
      }
      /**
       * <code>.tutorial.CoreAccountDTO coreAccountDTO = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          n3.sail.protobuf.schema.UserCacheSchema.CoreAccountDTO, n3.sail.protobuf.schema.UserCacheSchema.CoreAccountDTO.Builder, n3.sail.protobuf.schema.UserCacheSchema.CoreAccountDTOOrBuilder> 
          getCoreAccountDTOFieldBuilder() {
        if (coreAccountDTOBuilder_ == null) {
          coreAccountDTOBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              n3.sail.protobuf.schema.UserCacheSchema.CoreAccountDTO, n3.sail.protobuf.schema.UserCacheSchema.CoreAccountDTO.Builder, n3.sail.protobuf.schema.UserCacheSchema.CoreAccountDTOOrBuilder>(
                  getCoreAccountDTO(),
                  getParentForChildren(),
                  isClean());
          coreAccountDTO_ = null;
        }
        return coreAccountDTOBuilder_;
      }

      private n3.sail.protobuf.schema.UserCacheSchema.OperatorDTO operatorDTO_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          n3.sail.protobuf.schema.UserCacheSchema.OperatorDTO, n3.sail.protobuf.schema.UserCacheSchema.OperatorDTO.Builder, n3.sail.protobuf.schema.UserCacheSchema.OperatorDTOOrBuilder> operatorDTOBuilder_;
      /**
       * <code>.tutorial.OperatorDTO operatorDTO = 2;</code>
       */
      public boolean hasOperatorDTO() {
        return operatorDTOBuilder_ != null || operatorDTO_ != null;
      }
      /**
       * <code>.tutorial.OperatorDTO operatorDTO = 2;</code>
       */
      public n3.sail.protobuf.schema.UserCacheSchema.OperatorDTO getOperatorDTO() {
        if (operatorDTOBuilder_ == null) {
          return operatorDTO_ == null ? n3.sail.protobuf.schema.UserCacheSchema.OperatorDTO.getDefaultInstance() : operatorDTO_;
        } else {
          return operatorDTOBuilder_.getMessage();
        }
      }
      /**
       * <code>.tutorial.OperatorDTO operatorDTO = 2;</code>
       */
      public Builder setOperatorDTO(n3.sail.protobuf.schema.UserCacheSchema.OperatorDTO value) {
        if (operatorDTOBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          operatorDTO_ = value;
          onChanged();
        } else {
          operatorDTOBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.tutorial.OperatorDTO operatorDTO = 2;</code>
       */
      public Builder setOperatorDTO(
          n3.sail.protobuf.schema.UserCacheSchema.OperatorDTO.Builder builderForValue) {
        if (operatorDTOBuilder_ == null) {
          operatorDTO_ = builderForValue.build();
          onChanged();
        } else {
          operatorDTOBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.tutorial.OperatorDTO operatorDTO = 2;</code>
       */
      public Builder mergeOperatorDTO(n3.sail.protobuf.schema.UserCacheSchema.OperatorDTO value) {
        if (operatorDTOBuilder_ == null) {
          if (operatorDTO_ != null) {
            operatorDTO_ =
              n3.sail.protobuf.schema.UserCacheSchema.OperatorDTO.newBuilder(operatorDTO_).mergeFrom(value).buildPartial();
          } else {
            operatorDTO_ = value;
          }
          onChanged();
        } else {
          operatorDTOBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.tutorial.OperatorDTO operatorDTO = 2;</code>
       */
      public Builder clearOperatorDTO() {
        if (operatorDTOBuilder_ == null) {
          operatorDTO_ = null;
          onChanged();
        } else {
          operatorDTO_ = null;
          operatorDTOBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.tutorial.OperatorDTO operatorDTO = 2;</code>
       */
      public n3.sail.protobuf.schema.UserCacheSchema.OperatorDTO.Builder getOperatorDTOBuilder() {
        
        onChanged();
        return getOperatorDTOFieldBuilder().getBuilder();
      }
      /**
       * <code>.tutorial.OperatorDTO operatorDTO = 2;</code>
       */
      public n3.sail.protobuf.schema.UserCacheSchema.OperatorDTOOrBuilder getOperatorDTOOrBuilder() {
        if (operatorDTOBuilder_ != null) {
          return operatorDTOBuilder_.getMessageOrBuilder();
        } else {
          return operatorDTO_ == null ?
              n3.sail.protobuf.schema.UserCacheSchema.OperatorDTO.getDefaultInstance() : operatorDTO_;
        }
      }
      /**
       * <code>.tutorial.OperatorDTO operatorDTO = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          n3.sail.protobuf.schema.UserCacheSchema.OperatorDTO, n3.sail.protobuf.schema.UserCacheSchema.OperatorDTO.Builder, n3.sail.protobuf.schema.UserCacheSchema.OperatorDTOOrBuilder> 
          getOperatorDTOFieldBuilder() {
        if (operatorDTOBuilder_ == null) {
          operatorDTOBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              n3.sail.protobuf.schema.UserCacheSchema.OperatorDTO, n3.sail.protobuf.schema.UserCacheSchema.OperatorDTO.Builder, n3.sail.protobuf.schema.UserCacheSchema.OperatorDTOOrBuilder>(
                  getOperatorDTO(),
                  getParentForChildren(),
                  isClean());
          operatorDTO_ = null;
        }
        return operatorDTOBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:tutorial.UserCacheDTO)
    }

    // @@protoc_insertion_point(class_scope:tutorial.UserCacheDTO)
    private static final n3.sail.protobuf.schema.UserCacheSchema.UserCacheDTO DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new n3.sail.protobuf.schema.UserCacheSchema.UserCacheDTO();
    }

    public static n3.sail.protobuf.schema.UserCacheSchema.UserCacheDTO getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<UserCacheDTO>
        PARSER = new com.google.protobuf.AbstractParser<UserCacheDTO>() {
      public UserCacheDTO parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new UserCacheDTO(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<UserCacheDTO> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<UserCacheDTO> getParserForType() {
      return PARSER;
    }

    public n3.sail.protobuf.schema.UserCacheSchema.UserCacheDTO getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface CoreAccountDTOOrBuilder extends
      // @@protoc_insertion_point(interface_extends:tutorial.CoreAccountDTO)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string coreAccountId = 1;</code>
     */
    java.lang.String getCoreAccountId();
    /**
     * <code>string coreAccountId = 1;</code>
     */
    com.google.protobuf.ByteString
        getCoreAccountIdBytes();

    /**
     * <code>string status = 2;</code>
     */
    java.lang.String getStatus();
    /**
     * <code>string status = 2;</code>
     */
    com.google.protobuf.ByteString
        getStatusBytes();
  }
  /**
   * Protobuf type {@code tutorial.CoreAccountDTO}
   */
  public  static final class CoreAccountDTO extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:tutorial.CoreAccountDTO)
      CoreAccountDTOOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use CoreAccountDTO.newBuilder() to construct.
    private CoreAccountDTO(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CoreAccountDTO() {
      coreAccountId_ = "";
      status_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private CoreAccountDTO(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              coreAccountId_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              status_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return n3.sail.protobuf.schema.UserCacheSchema.internal_static_tutorial_CoreAccountDTO_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return n3.sail.protobuf.schema.UserCacheSchema.internal_static_tutorial_CoreAccountDTO_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              n3.sail.protobuf.schema.UserCacheSchema.CoreAccountDTO.class, n3.sail.protobuf.schema.UserCacheSchema.CoreAccountDTO.Builder.class);
    }

    public static final int COREACCOUNTID_FIELD_NUMBER = 1;
    private volatile java.lang.Object coreAccountId_;
    /**
     * <code>string coreAccountId = 1;</code>
     */
    public java.lang.String getCoreAccountId() {
      java.lang.Object ref = coreAccountId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        coreAccountId_ = s;
        return s;
      }
    }
    /**
     * <code>string coreAccountId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getCoreAccountIdBytes() {
      java.lang.Object ref = coreAccountId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        coreAccountId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int STATUS_FIELD_NUMBER = 2;
    private volatile java.lang.Object status_;
    /**
     * <code>string status = 2;</code>
     */
    public java.lang.String getStatus() {
      java.lang.Object ref = status_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        status_ = s;
        return s;
      }
    }
    /**
     * <code>string status = 2;</code>
     */
    public com.google.protobuf.ByteString
        getStatusBytes() {
      java.lang.Object ref = status_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        status_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getCoreAccountIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, coreAccountId_);
      }
      if (!getStatusBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, status_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getCoreAccountIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, coreAccountId_);
      }
      if (!getStatusBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, status_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof n3.sail.protobuf.schema.UserCacheSchema.CoreAccountDTO)) {
        return super.equals(obj);
      }
      n3.sail.protobuf.schema.UserCacheSchema.CoreAccountDTO other = (n3.sail.protobuf.schema.UserCacheSchema.CoreAccountDTO) obj;

      boolean result = true;
      result = result && getCoreAccountId()
          .equals(other.getCoreAccountId());
      result = result && getStatus()
          .equals(other.getStatus());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + COREACCOUNTID_FIELD_NUMBER;
      hash = (53 * hash) + getCoreAccountId().hashCode();
      hash = (37 * hash) + STATUS_FIELD_NUMBER;
      hash = (53 * hash) + getStatus().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static n3.sail.protobuf.schema.UserCacheSchema.CoreAccountDTO parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static n3.sail.protobuf.schema.UserCacheSchema.CoreAccountDTO parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static n3.sail.protobuf.schema.UserCacheSchema.CoreAccountDTO parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static n3.sail.protobuf.schema.UserCacheSchema.CoreAccountDTO parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static n3.sail.protobuf.schema.UserCacheSchema.CoreAccountDTO parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static n3.sail.protobuf.schema.UserCacheSchema.CoreAccountDTO parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static n3.sail.protobuf.schema.UserCacheSchema.CoreAccountDTO parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static n3.sail.protobuf.schema.UserCacheSchema.CoreAccountDTO parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static n3.sail.protobuf.schema.UserCacheSchema.CoreAccountDTO parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static n3.sail.protobuf.schema.UserCacheSchema.CoreAccountDTO parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static n3.sail.protobuf.schema.UserCacheSchema.CoreAccountDTO parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static n3.sail.protobuf.schema.UserCacheSchema.CoreAccountDTO parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(n3.sail.protobuf.schema.UserCacheSchema.CoreAccountDTO prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code tutorial.CoreAccountDTO}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:tutorial.CoreAccountDTO)
        n3.sail.protobuf.schema.UserCacheSchema.CoreAccountDTOOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return n3.sail.protobuf.schema.UserCacheSchema.internal_static_tutorial_CoreAccountDTO_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return n3.sail.protobuf.schema.UserCacheSchema.internal_static_tutorial_CoreAccountDTO_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                n3.sail.protobuf.schema.UserCacheSchema.CoreAccountDTO.class, n3.sail.protobuf.schema.UserCacheSchema.CoreAccountDTO.Builder.class);
      }

      // Construct using n3.sail.protobuf.schema.UserCacheSchema.CoreAccountDTO.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        coreAccountId_ = "";

        status_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return n3.sail.protobuf.schema.UserCacheSchema.internal_static_tutorial_CoreAccountDTO_descriptor;
      }

      public n3.sail.protobuf.schema.UserCacheSchema.CoreAccountDTO getDefaultInstanceForType() {
        return n3.sail.protobuf.schema.UserCacheSchema.CoreAccountDTO.getDefaultInstance();
      }

      public n3.sail.protobuf.schema.UserCacheSchema.CoreAccountDTO build() {
        n3.sail.protobuf.schema.UserCacheSchema.CoreAccountDTO result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public n3.sail.protobuf.schema.UserCacheSchema.CoreAccountDTO buildPartial() {
        n3.sail.protobuf.schema.UserCacheSchema.CoreAccountDTO result = new n3.sail.protobuf.schema.UserCacheSchema.CoreAccountDTO(this);
        result.coreAccountId_ = coreAccountId_;
        result.status_ = status_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof n3.sail.protobuf.schema.UserCacheSchema.CoreAccountDTO) {
          return mergeFrom((n3.sail.protobuf.schema.UserCacheSchema.CoreAccountDTO)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(n3.sail.protobuf.schema.UserCacheSchema.CoreAccountDTO other) {
        if (other == n3.sail.protobuf.schema.UserCacheSchema.CoreAccountDTO.getDefaultInstance()) return this;
        if (!other.getCoreAccountId().isEmpty()) {
          coreAccountId_ = other.coreAccountId_;
          onChanged();
        }
        if (!other.getStatus().isEmpty()) {
          status_ = other.status_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        n3.sail.protobuf.schema.UserCacheSchema.CoreAccountDTO parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (n3.sail.protobuf.schema.UserCacheSchema.CoreAccountDTO) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object coreAccountId_ = "";
      /**
       * <code>string coreAccountId = 1;</code>
       */
      public java.lang.String getCoreAccountId() {
        java.lang.Object ref = coreAccountId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          coreAccountId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string coreAccountId = 1;</code>
       */
      public com.google.protobuf.ByteString
          getCoreAccountIdBytes() {
        java.lang.Object ref = coreAccountId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          coreAccountId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string coreAccountId = 1;</code>
       */
      public Builder setCoreAccountId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        coreAccountId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string coreAccountId = 1;</code>
       */
      public Builder clearCoreAccountId() {
        
        coreAccountId_ = getDefaultInstance().getCoreAccountId();
        onChanged();
        return this;
      }
      /**
       * <code>string coreAccountId = 1;</code>
       */
      public Builder setCoreAccountIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        coreAccountId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object status_ = "";
      /**
       * <code>string status = 2;</code>
       */
      public java.lang.String getStatus() {
        java.lang.Object ref = status_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          status_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string status = 2;</code>
       */
      public com.google.protobuf.ByteString
          getStatusBytes() {
        java.lang.Object ref = status_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          status_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string status = 2;</code>
       */
      public Builder setStatus(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        status_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string status = 2;</code>
       */
      public Builder clearStatus() {
        
        status_ = getDefaultInstance().getStatus();
        onChanged();
        return this;
      }
      /**
       * <code>string status = 2;</code>
       */
      public Builder setStatusBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        status_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:tutorial.CoreAccountDTO)
    }

    // @@protoc_insertion_point(class_scope:tutorial.CoreAccountDTO)
    private static final n3.sail.protobuf.schema.UserCacheSchema.CoreAccountDTO DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new n3.sail.protobuf.schema.UserCacheSchema.CoreAccountDTO();
    }

    public static n3.sail.protobuf.schema.UserCacheSchema.CoreAccountDTO getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CoreAccountDTO>
        PARSER = new com.google.protobuf.AbstractParser<CoreAccountDTO>() {
      public CoreAccountDTO parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new CoreAccountDTO(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CoreAccountDTO> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CoreAccountDTO> getParserForType() {
      return PARSER;
    }

    public n3.sail.protobuf.schema.UserCacheSchema.CoreAccountDTO getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface OperatorDTOOrBuilder extends
      // @@protoc_insertion_point(interface_extends:tutorial.OperatorDTO)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string operatorId = 1;</code>
     */
    java.lang.String getOperatorId();
    /**
     * <code>string operatorId = 1;</code>
     */
    com.google.protobuf.ByteString
        getOperatorIdBytes();

    /**
     * <code>string type = 2;</code>
     */
    java.lang.String getType();
    /**
     * <code>string type = 2;</code>
     */
    com.google.protobuf.ByteString
        getTypeBytes();
  }
  /**
   * Protobuf type {@code tutorial.OperatorDTO}
   */
  public  static final class OperatorDTO extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:tutorial.OperatorDTO)
      OperatorDTOOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use OperatorDTO.newBuilder() to construct.
    private OperatorDTO(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private OperatorDTO() {
      operatorId_ = "";
      type_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private OperatorDTO(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              operatorId_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              type_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return n3.sail.protobuf.schema.UserCacheSchema.internal_static_tutorial_OperatorDTO_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return n3.sail.protobuf.schema.UserCacheSchema.internal_static_tutorial_OperatorDTO_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              n3.sail.protobuf.schema.UserCacheSchema.OperatorDTO.class, n3.sail.protobuf.schema.UserCacheSchema.OperatorDTO.Builder.class);
    }

    public static final int OPERATORID_FIELD_NUMBER = 1;
    private volatile java.lang.Object operatorId_;
    /**
     * <code>string operatorId = 1;</code>
     */
    public java.lang.String getOperatorId() {
      java.lang.Object ref = operatorId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        operatorId_ = s;
        return s;
      }
    }
    /**
     * <code>string operatorId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getOperatorIdBytes() {
      java.lang.Object ref = operatorId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        operatorId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TYPE_FIELD_NUMBER = 2;
    private volatile java.lang.Object type_;
    /**
     * <code>string type = 2;</code>
     */
    public java.lang.String getType() {
      java.lang.Object ref = type_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        type_ = s;
        return s;
      }
    }
    /**
     * <code>string type = 2;</code>
     */
    public com.google.protobuf.ByteString
        getTypeBytes() {
      java.lang.Object ref = type_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        type_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getOperatorIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, operatorId_);
      }
      if (!getTypeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, type_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getOperatorIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, operatorId_);
      }
      if (!getTypeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, type_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof n3.sail.protobuf.schema.UserCacheSchema.OperatorDTO)) {
        return super.equals(obj);
      }
      n3.sail.protobuf.schema.UserCacheSchema.OperatorDTO other = (n3.sail.protobuf.schema.UserCacheSchema.OperatorDTO) obj;

      boolean result = true;
      result = result && getOperatorId()
          .equals(other.getOperatorId());
      result = result && getType()
          .equals(other.getType());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + OPERATORID_FIELD_NUMBER;
      hash = (53 * hash) + getOperatorId().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getType().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static n3.sail.protobuf.schema.UserCacheSchema.OperatorDTO parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static n3.sail.protobuf.schema.UserCacheSchema.OperatorDTO parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static n3.sail.protobuf.schema.UserCacheSchema.OperatorDTO parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static n3.sail.protobuf.schema.UserCacheSchema.OperatorDTO parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static n3.sail.protobuf.schema.UserCacheSchema.OperatorDTO parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static n3.sail.protobuf.schema.UserCacheSchema.OperatorDTO parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static n3.sail.protobuf.schema.UserCacheSchema.OperatorDTO parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static n3.sail.protobuf.schema.UserCacheSchema.OperatorDTO parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static n3.sail.protobuf.schema.UserCacheSchema.OperatorDTO parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static n3.sail.protobuf.schema.UserCacheSchema.OperatorDTO parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static n3.sail.protobuf.schema.UserCacheSchema.OperatorDTO parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static n3.sail.protobuf.schema.UserCacheSchema.OperatorDTO parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(n3.sail.protobuf.schema.UserCacheSchema.OperatorDTO prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code tutorial.OperatorDTO}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:tutorial.OperatorDTO)
        n3.sail.protobuf.schema.UserCacheSchema.OperatorDTOOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return n3.sail.protobuf.schema.UserCacheSchema.internal_static_tutorial_OperatorDTO_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return n3.sail.protobuf.schema.UserCacheSchema.internal_static_tutorial_OperatorDTO_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                n3.sail.protobuf.schema.UserCacheSchema.OperatorDTO.class, n3.sail.protobuf.schema.UserCacheSchema.OperatorDTO.Builder.class);
      }

      // Construct using n3.sail.protobuf.schema.UserCacheSchema.OperatorDTO.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        operatorId_ = "";

        type_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return n3.sail.protobuf.schema.UserCacheSchema.internal_static_tutorial_OperatorDTO_descriptor;
      }

      public n3.sail.protobuf.schema.UserCacheSchema.OperatorDTO getDefaultInstanceForType() {
        return n3.sail.protobuf.schema.UserCacheSchema.OperatorDTO.getDefaultInstance();
      }

      public n3.sail.protobuf.schema.UserCacheSchema.OperatorDTO build() {
        n3.sail.protobuf.schema.UserCacheSchema.OperatorDTO result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public n3.sail.protobuf.schema.UserCacheSchema.OperatorDTO buildPartial() {
        n3.sail.protobuf.schema.UserCacheSchema.OperatorDTO result = new n3.sail.protobuf.schema.UserCacheSchema.OperatorDTO(this);
        result.operatorId_ = operatorId_;
        result.type_ = type_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof n3.sail.protobuf.schema.UserCacheSchema.OperatorDTO) {
          return mergeFrom((n3.sail.protobuf.schema.UserCacheSchema.OperatorDTO)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(n3.sail.protobuf.schema.UserCacheSchema.OperatorDTO other) {
        if (other == n3.sail.protobuf.schema.UserCacheSchema.OperatorDTO.getDefaultInstance()) return this;
        if (!other.getOperatorId().isEmpty()) {
          operatorId_ = other.operatorId_;
          onChanged();
        }
        if (!other.getType().isEmpty()) {
          type_ = other.type_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        n3.sail.protobuf.schema.UserCacheSchema.OperatorDTO parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (n3.sail.protobuf.schema.UserCacheSchema.OperatorDTO) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object operatorId_ = "";
      /**
       * <code>string operatorId = 1;</code>
       */
      public java.lang.String getOperatorId() {
        java.lang.Object ref = operatorId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          operatorId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string operatorId = 1;</code>
       */
      public com.google.protobuf.ByteString
          getOperatorIdBytes() {
        java.lang.Object ref = operatorId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          operatorId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string operatorId = 1;</code>
       */
      public Builder setOperatorId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        operatorId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string operatorId = 1;</code>
       */
      public Builder clearOperatorId() {
        
        operatorId_ = getDefaultInstance().getOperatorId();
        onChanged();
        return this;
      }
      /**
       * <code>string operatorId = 1;</code>
       */
      public Builder setOperatorIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        operatorId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object type_ = "";
      /**
       * <code>string type = 2;</code>
       */
      public java.lang.String getType() {
        java.lang.Object ref = type_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          type_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string type = 2;</code>
       */
      public com.google.protobuf.ByteString
          getTypeBytes() {
        java.lang.Object ref = type_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          type_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string type = 2;</code>
       */
      public Builder setType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string type = 2;</code>
       */
      public Builder clearType() {
        
        type_ = getDefaultInstance().getType();
        onChanged();
        return this;
      }
      /**
       * <code>string type = 2;</code>
       */
      public Builder setTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        type_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:tutorial.OperatorDTO)
    }

    // @@protoc_insertion_point(class_scope:tutorial.OperatorDTO)
    private static final n3.sail.protobuf.schema.UserCacheSchema.OperatorDTO DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new n3.sail.protobuf.schema.UserCacheSchema.OperatorDTO();
    }

    public static n3.sail.protobuf.schema.UserCacheSchema.OperatorDTO getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<OperatorDTO>
        PARSER = new com.google.protobuf.AbstractParser<OperatorDTO>() {
      public OperatorDTO parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new OperatorDTO(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<OperatorDTO> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<OperatorDTO> getParserForType() {
      return PARSER;
    }

    public n3.sail.protobuf.schema.UserCacheSchema.OperatorDTO getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tutorial_UserCacheDTO_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tutorial_UserCacheDTO_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tutorial_CoreAccountDTO_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tutorial_CoreAccountDTO_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tutorial_OperatorDTO_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tutorial_OperatorDTO_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017UserCache.proto\022\010tutorial\"l\n\014UserCache" +
      "DTO\0220\n\016coreAccountDTO\030\001 \001(\0132\030.tutorial.C" +
      "oreAccountDTO\022*\n\013operatorDTO\030\002 \001(\0132\025.tut" +
      "orial.OperatorDTO\"7\n\016CoreAccountDTO\022\025\n\rc" +
      "oreAccountId\030\001 \001(\t\022\016\n\006status\030\002 \001(\t\"/\n\013Op" +
      "eratorDTO\022\022\n\noperatorId\030\001 \001(\t\022\014\n\004type\030\002 " +
      "\001(\tB*\n\027n3.sail.protobuf.schemaB\017UserCach" +
      "eSchemab\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_tutorial_UserCacheDTO_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_tutorial_UserCacheDTO_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tutorial_UserCacheDTO_descriptor,
        new java.lang.String[] { "CoreAccountDTO", "OperatorDTO", });
    internal_static_tutorial_CoreAccountDTO_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_tutorial_CoreAccountDTO_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tutorial_CoreAccountDTO_descriptor,
        new java.lang.String[] { "CoreAccountId", "Status", });
    internal_static_tutorial_OperatorDTO_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_tutorial_OperatorDTO_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tutorial_OperatorDTO_descriptor,
        new java.lang.String[] { "OperatorId", "Type", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
